[package]
name = "druid-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vfc = {path = "../vfc"}
async-trait = "0.1"
game-loop = "0.10"