[package]
name = "vfc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vfc"           # The name of the target.
path = "src/lib/vfc.rs"    # The source file of the target.

[dependencies]

